### ISSUE TITLE
Private Posts do not appear in Search Posts select2

### ISSUE THREAD

**Issue by jeffpaul** [xwp/wp-customize-posts#344] opened 2017-01-27 19:17 UTC
Steps to reproduce:
1) Create a private post.
2) Open Customizer, Posts section
3) Search for name of previously created private post, see message below.
![private-post-search-issue](https://cloud.githubusercontent.com/assets/2818133/22384098/6eb7d3b0-e492-11e6-85e7-e70d70cb4fa8.jpg)

Actual outcome:
"No results found" message is displayed beneath the "Search Posts" select2.

Expected outcome:
"PRIVATE Post Title" post appears in "Search Posts" select2 and can be appropriately customized.

**Comment by westonruter** [comment] 2017-02-01 05:47
@jeffpaul Humm. I'm not able to reproduce this issue. I created a post with the “PRIVATE Post Title” and it appears as expected:

![image](https://cloud.githubusercontent.com/assets/134745/22496454/c0171bc0-e7fe-11e6-9842-4db1e070dabd.png)

![image](https://cloud.githubusercontent.com/assets/134745/22496465/cf7f302a-e7fe-11e6-96f9-fe4eb99efc84.png)

![image](https://cloud.githubusercontent.com/assets/134745/22496473/df9b9516-e7fe-11e6-956f-145665c306ad.png)

**Comment by jeffpaul** [comment] 2017-02-01 17:55
@westonruter that is odd, potentially related to other plugin(s) in the environment then. Seems like @sayedwp can replicate it though, so he's going to research to find the root cause.

**Comment by sayedtaqui** [comment] 2017-04-04 13:05
I had figured out that it was due to some other plugin, not a customize-posts issue, so closing the ticket.

**Closed by sayedtaqui** 2017-04-04 13:05 UTC
Labels: bug
